services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongpwd
    ports:
     - 27018:27018
    volumes:
     - mongodata:/var/lib/mongodb/data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: silasgah/auction:latest
    build:
      context: .
      dockerfile: src/StudentService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=auction
      - IdentityServiceUrl=http://identity-svc
    ports:
     - 7001:80
    depends_on:
     - postgres
     - rabbitmq
  search-svc:
    image: silasgah/search:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongpwd@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
     - 7002:80
    depends_on:
     - mongodb
     - rabbitmq
  identity-svc:
    image: silasgah/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=identity
    ports:
     - 5001:80
    depends_on:
     - postgres
  
  gateway-svc:
    image: silasgah/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
     - 6001:80
     
volumes:
  pgdata:
  mongodata: