services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongpwd
    ports:
     - 27018:27018
    volumes:
     - mongodata:/var/lib/mongodb/data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
      



volumes:
  pgdata:
  mongodata: