import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./Nav/navbar";


export const metadata: Metadata = {
  title: "RGD App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <Navbar />
         <main className="container mx-auto px-5 pt-10">
        {children}
        </main>
        </body>
    
    </html>
  );
}
